data_source:
  type: yfinance
  tickers:                  # Add one or more Yahoo Finance tickers
    - "0P0001ANWB.BO"
    - "NIFTYBEES.NS"

sip:
  monthly_amount: 5000
  default_date: 5

backtest:
  start_date: "2021-01-01"
  end_date: "2026-03-28"

sip_optimization:
  enabled: true
  analyze_dates: []
  top_n: 5                  # Number of top SIP dates to display

cert_path: "~/.config/cert/cacert.crt"