data_source:
  type: yfinance
  tickers:                  # List of Yahoo Finance tickers to analyze (one or more)
    - "0P0000XW8F.BO"
    - "0P0001BAYH.BO"
    - "0P0000XWAT.BO"

sip:
  monthly_amount: 5000
  default_date: 5

backtest:
  start_date: "2023-02-01"
  end_date: "2026-02-28"

sip_optimization:
  enabled: true
  analyze_dates: []
  top_n: 5                  # Number of top SIP dates to display (default: 3)

cert_path: "~/.config/cert/cacert.crt"
